### ISSUE TITLE
Blocked Staff Chat Messages Sent To Public Channels

### ISSUE THREAD

**Issue by HyxonQz** [aidn3/hypixel-guild-discord-bridge#36]
If a message that is blocked by hypixel's filter is sent via a discord officer chat, the error is sent as an embed to the public bridge channels including the uncensored message

**Comment by aidn3** [comment]
So, you want the bridge to treat "blocked message" event differently based on its origin.

The bridge supports cluster mode. Due to this mode, the events such as "message sent" and "message got blocked" can't be guaranteed to be processed in sequence. In other words, it can't predict or know the origin of anything. 

This problem also exist in "can't repeat the same message!" event. It can't detect on which channel the message has been sent and hence can't route it to its intended channel. Instead it is sent to the public channel as well.

The best it can be done is identify "blocked message" event and blur its content and display a generic message instead.
