### ISSUE TITLE
.env_example isn't a real file

### ISSUE THREAD

**Issue by RagingEnby** [aidn3/hypixel-guild-discord-bridge#37]
In quite a few spots of the documentation I see "set this in .env" and one mentions using ".env_example" but I see neither of these files anywhere.

**Comment by aidn3** [comment]
A mistake on my part. I'll fix the documentation and tag it as a released version soon.

For now: You can either download [from latest releases](https://github.com/aidn3/hypixel-guild-discord-bridge/releases) instead if you wish to stick to the old documentations. OR, you can try the new configuration format `config_example.yaml` in the latest updates.

The current reporisotry has many major updates and many advanced features. The new configuration format has become [config_example.yaml](https://github.com/aidn3/hypixel-guild-discord-bridge/blob/master/config_example.yaml).
Make a copy and rename it `config.yaml` instead of `.env`. The configuration shouldn't be much different from the old one.
I know the new configuration has more "moving parts" and looks complicated. Be assured, default settings are optimal. Just change `Discord` and `Minecraft` config in the file.
